name: "Macos Telegram Action"
description: "Macos Telegram action"

inputs:
  script:
    description: "Script to run"
    inputs:
      type:
        description: "Your type: group, topic, channel"
        required: true
      message:
        description: "Your message you want to send to telegram"
        required: true

runs:
  using: "composite"
  steps:
    - name: Init Macos Telegram Action
      shell: bash
      run: |
        source ${{ github.action_path }}/index.sh
        health_check

    - name: Send to group
      if: ${{ inputs.type == "group" }}
      run: send_telegram_group "${{ inputs.message }}"

    - name: Send to topic
      if: ${{ inputs.type == "group" }}
      run: send_telegram_group_topic "${{ inputs.message }}"

    - name: Send to channel
      if: ${{ inputs.type == "group" }}
      run: send_telegram_channel "${{ inputs.message }}"
